### ISSUE TITLE
Question: Is it save to call artnet.parse() with some delay?

### ISSUE THREAD

**Issue by 60pfennig** [hideakitai/ArtNet#31] opened 2022-02-05 20:27 UTC
Hi, thanks for your good library! 
I'm using FastLED with Artnet on an ESP32 with ESP-IDF and Arduino as component.
I have a Artnet read task and a Fastled show task. The read task is filling the buffer and syncs with the fastled.show() task to let it push the data to the stripe.
To free up ressources I tried to pause the Artnet read task to start 22ms after last execution because Artnet has 44FPS max framerate. So 1000/44 ~= 22
The problem is that I get lags. It looks that some frame getting dropped sometimes. But even without delaying the task I get some drops. So I'm asking myself if the problem is the delay of the tasks(are new packets "overriding" old ones which didn't got handled by the callback yet?) , the network (losing some packets) or the syncing between the tasks (I have put everything in the same task, but it lagged anyway). Even if I think it is a problem of the network (using an Android hotspot), I'm curious about the the question if I can pause the task for some time?

**Comment by hideakitai** [comment] 2022-03-07 10:16
@60pfennig Hi, sorry for the late reply. 
Since we do not know the details, we cannot determine the cause. However, as a general rule, some packets will be skipped if you let the tasks sleep and packets are queued. However, if the packets are coming in at precisely 44 FPS, the maximum number of packets that will be skipped is probably one packet. 
Sorry, but I'm going to close this now, but if you still have questions, feel free to re-open it.

**Closed by hideakitai** 2022-03-07 10:16 UTC
